version: "3"
services:
 ganache:
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "8545:8545"
 smart-contracts:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ganache